// Generated by gencpp from file master_thesis_kremmel/LandmarkRequest.msg
// DO NOT EDIT!


#ifndef MASTER_THESIS_KREMMEL_MESSAGE_LANDMARKREQUEST_H
#define MASTER_THESIS_KREMMEL_MESSAGE_LANDMARKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/PointCloud2.h>

namespace master_thesis_kremmel
{
template <class ContainerAllocator>
struct LandmarkRequest_
{
  typedef LandmarkRequest_<ContainerAllocator> Type;

  LandmarkRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , points()  {
    }
  LandmarkRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::master_thesis_kremmel::LandmarkRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::master_thesis_kremmel::LandmarkRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LandmarkRequest_

typedef ::master_thesis_kremmel::LandmarkRequest_<std::allocator<void> > LandmarkRequest;

typedef boost::shared_ptr< ::master_thesis_kremmel::LandmarkRequest > LandmarkRequestPtr;
typedef boost::shared_ptr< ::master_thesis_kremmel::LandmarkRequest const> LandmarkRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::master_thesis_kremmel::LandmarkRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::master_thesis_kremmel::LandmarkRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::master_thesis_kremmel::LandmarkRequest_<ContainerAllocator1> & lhs, const ::master_thesis_kremmel::LandmarkRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::master_thesis_kremmel::LandmarkRequest_<ContainerAllocator1> & lhs, const ::master_thesis_kremmel::LandmarkRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace master_thesis_kremmel

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::master_thesis_kremmel::LandmarkRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master_thesis_kremmel::LandmarkRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::master_thesis_kremmel::LandmarkRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::master_thesis_kremmel::LandmarkRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_thesis_kremmel::LandmarkRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_thesis_kremmel::LandmarkRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::master_thesis_kremmel::LandmarkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1dc082e1fbecafe6eb3b98df48c83377";
  }

  static const char* value(const ::master_thesis_kremmel::LandmarkRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1dc082e1fbecafe6ULL;
  static const uint64_t static_value2 = 0xeb3b98df48c83377ULL;
};

template<class ContainerAllocator>
struct DataType< ::master_thesis_kremmel::LandmarkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "master_thesis_kremmel/LandmarkRequest";
  }

  static const char* value(const ::master_thesis_kremmel::LandmarkRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::master_thesis_kremmel::LandmarkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
"sensor_msgs/PointCloud2 points\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
;
  }

  static const char* value(const ::master_thesis_kremmel::LandmarkRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::master_thesis_kremmel::LandmarkRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LandmarkRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::master_thesis_kremmel::LandmarkRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::master_thesis_kremmel::LandmarkRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "points: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.points);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MASTER_THESIS_KREMMEL_MESSAGE_LANDMARKREQUEST_H
