// Generated by gencpp from file master_thesis_kremmel/Landmark.msg
// DO NOT EDIT!


#ifndef MASTER_THESIS_KREMMEL_MESSAGE_LANDMARK_H
#define MASTER_THESIS_KREMMEL_MESSAGE_LANDMARK_H

#include <ros/service_traits.h>


#include <master_thesis_kremmel/LandmarkRequest.h>
#include <master_thesis_kremmel/LandmarkResponse.h>


namespace master_thesis_kremmel
{

struct Landmark
{

typedef LandmarkRequest Request;
typedef LandmarkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Landmark
} // namespace master_thesis_kremmel


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::master_thesis_kremmel::Landmark > {
  static const char* value()
  {
    return "660e396741d234fed172fa08d86c0fb0";
  }

  static const char* value(const ::master_thesis_kremmel::Landmark&) { return value(); }
};

template<>
struct DataType< ::master_thesis_kremmel::Landmark > {
  static const char* value()
  {
    return "master_thesis_kremmel/Landmark";
  }

  static const char* value(const ::master_thesis_kremmel::Landmark&) { return value(); }
};


// service_traits::MD5Sum< ::master_thesis_kremmel::LandmarkRequest> should match
// service_traits::MD5Sum< ::master_thesis_kremmel::Landmark >
template<>
struct MD5Sum< ::master_thesis_kremmel::LandmarkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::master_thesis_kremmel::Landmark >::value();
  }
  static const char* value(const ::master_thesis_kremmel::LandmarkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_thesis_kremmel::LandmarkRequest> should match
// service_traits::DataType< ::master_thesis_kremmel::Landmark >
template<>
struct DataType< ::master_thesis_kremmel::LandmarkRequest>
{
  static const char* value()
  {
    return DataType< ::master_thesis_kremmel::Landmark >::value();
  }
  static const char* value(const ::master_thesis_kremmel::LandmarkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::master_thesis_kremmel::LandmarkResponse> should match
// service_traits::MD5Sum< ::master_thesis_kremmel::Landmark >
template<>
struct MD5Sum< ::master_thesis_kremmel::LandmarkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::master_thesis_kremmel::Landmark >::value();
  }
  static const char* value(const ::master_thesis_kremmel::LandmarkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_thesis_kremmel::LandmarkResponse> should match
// service_traits::DataType< ::master_thesis_kremmel::Landmark >
template<>
struct DataType< ::master_thesis_kremmel::LandmarkResponse>
{
  static const char* value()
  {
    return DataType< ::master_thesis_kremmel::Landmark >::value();
  }
  static const char* value(const ::master_thesis_kremmel::LandmarkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASTER_THESIS_KREMMEL_MESSAGE_LANDMARK_H
