// Generated by gencpp from file master_thesis_kremmel/MoveRobotRequest.msg
// DO NOT EDIT!


#ifndef MASTER_THESIS_KREMMEL_MESSAGE_MOVEROBOTREQUEST_H
#define MASTER_THESIS_KREMMEL_MESSAGE_MOVEROBOTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace master_thesis_kremmel
{
template <class ContainerAllocator>
struct MoveRobotRequest_
{
  typedef MoveRobotRequest_<ContainerAllocator> Type;

  MoveRobotRequest_()
    : x(0.0)
    , y(0.0)
    , t(0.0)  {
    }
  MoveRobotRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , t(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _t_type;
  _t_type t;





  typedef boost::shared_ptr< ::master_thesis_kremmel::MoveRobotRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::master_thesis_kremmel::MoveRobotRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveRobotRequest_

typedef ::master_thesis_kremmel::MoveRobotRequest_<std::allocator<void> > MoveRobotRequest;

typedef boost::shared_ptr< ::master_thesis_kremmel::MoveRobotRequest > MoveRobotRequestPtr;
typedef boost::shared_ptr< ::master_thesis_kremmel::MoveRobotRequest const> MoveRobotRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::master_thesis_kremmel::MoveRobotRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::master_thesis_kremmel::MoveRobotRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::master_thesis_kremmel::MoveRobotRequest_<ContainerAllocator1> & lhs, const ::master_thesis_kremmel::MoveRobotRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.t == rhs.t;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::master_thesis_kremmel::MoveRobotRequest_<ContainerAllocator1> & lhs, const ::master_thesis_kremmel::MoveRobotRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace master_thesis_kremmel

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::master_thesis_kremmel::MoveRobotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master_thesis_kremmel::MoveRobotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::master_thesis_kremmel::MoveRobotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::master_thesis_kremmel::MoveRobotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_thesis_kremmel::MoveRobotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_thesis_kremmel::MoveRobotRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::master_thesis_kremmel::MoveRobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a28bd10bf2ad79a2c715f25c5a7ebd3";
  }

  static const char* value(const ::master_thesis_kremmel::MoveRobotRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a28bd10bf2ad79aULL;
  static const uint64_t static_value2 = 0x2c715f25c5a7ebd3ULL;
};

template<class ContainerAllocator>
struct DataType< ::master_thesis_kremmel::MoveRobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "master_thesis_kremmel/MoveRobotRequest";
  }

  static const char* value(const ::master_thesis_kremmel::MoveRobotRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::master_thesis_kremmel::MoveRobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 t\n"
;
  }

  static const char* value(const ::master_thesis_kremmel::MoveRobotRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::master_thesis_kremmel::MoveRobotRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.t);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveRobotRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::master_thesis_kremmel::MoveRobotRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::master_thesis_kremmel::MoveRobotRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "t: ";
    Printer<double>::stream(s, indent + "  ", v.t);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MASTER_THESIS_KREMMEL_MESSAGE_MOVEROBOTREQUEST_H
