// Generated by gencpp from file master_thesis_kremmel/MoveRobot.msg
// DO NOT EDIT!


#ifndef MASTER_THESIS_KREMMEL_MESSAGE_MOVEROBOT_H
#define MASTER_THESIS_KREMMEL_MESSAGE_MOVEROBOT_H

#include <ros/service_traits.h>


#include <master_thesis_kremmel/MoveRobotRequest.h>
#include <master_thesis_kremmel/MoveRobotResponse.h>


namespace master_thesis_kremmel
{

struct MoveRobot
{

typedef MoveRobotRequest Request;
typedef MoveRobotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveRobot
} // namespace master_thesis_kremmel


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::master_thesis_kremmel::MoveRobot > {
  static const char* value()
  {
    return "4a28bd10bf2ad79a2c715f25c5a7ebd3";
  }

  static const char* value(const ::master_thesis_kremmel::MoveRobot&) { return value(); }
};

template<>
struct DataType< ::master_thesis_kremmel::MoveRobot > {
  static const char* value()
  {
    return "master_thesis_kremmel/MoveRobot";
  }

  static const char* value(const ::master_thesis_kremmel::MoveRobot&) { return value(); }
};


// service_traits::MD5Sum< ::master_thesis_kremmel::MoveRobotRequest> should match
// service_traits::MD5Sum< ::master_thesis_kremmel::MoveRobot >
template<>
struct MD5Sum< ::master_thesis_kremmel::MoveRobotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::master_thesis_kremmel::MoveRobot >::value();
  }
  static const char* value(const ::master_thesis_kremmel::MoveRobotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_thesis_kremmel::MoveRobotRequest> should match
// service_traits::DataType< ::master_thesis_kremmel::MoveRobot >
template<>
struct DataType< ::master_thesis_kremmel::MoveRobotRequest>
{
  static const char* value()
  {
    return DataType< ::master_thesis_kremmel::MoveRobot >::value();
  }
  static const char* value(const ::master_thesis_kremmel::MoveRobotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::master_thesis_kremmel::MoveRobotResponse> should match
// service_traits::MD5Sum< ::master_thesis_kremmel::MoveRobot >
template<>
struct MD5Sum< ::master_thesis_kremmel::MoveRobotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::master_thesis_kremmel::MoveRobot >::value();
  }
  static const char* value(const ::master_thesis_kremmel::MoveRobotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_thesis_kremmel::MoveRobotResponse> should match
// service_traits::DataType< ::master_thesis_kremmel::MoveRobot >
template<>
struct DataType< ::master_thesis_kremmel::MoveRobotResponse>
{
  static const char* value()
  {
    return DataType< ::master_thesis_kremmel::MoveRobot >::value();
  }
  static const char* value(const ::master_thesis_kremmel::MoveRobotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASTER_THESIS_KREMMEL_MESSAGE_MOVEROBOT_H
