// Generated by gencpp from file master_thesis_kremmel/MoveRobotResponse.msg
// DO NOT EDIT!


#ifndef MASTER_THESIS_KREMMEL_MESSAGE_MOVEROBOTRESPONSE_H
#define MASTER_THESIS_KREMMEL_MESSAGE_MOVEROBOTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace master_thesis_kremmel
{
template <class ContainerAllocator>
struct MoveRobotResponse_
{
  typedef MoveRobotResponse_<ContainerAllocator> Type;

  MoveRobotResponse_()
    {
    }
  MoveRobotResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::master_thesis_kremmel::MoveRobotResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::master_thesis_kremmel::MoveRobotResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveRobotResponse_

typedef ::master_thesis_kremmel::MoveRobotResponse_<std::allocator<void> > MoveRobotResponse;

typedef boost::shared_ptr< ::master_thesis_kremmel::MoveRobotResponse > MoveRobotResponsePtr;
typedef boost::shared_ptr< ::master_thesis_kremmel::MoveRobotResponse const> MoveRobotResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::master_thesis_kremmel::MoveRobotResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::master_thesis_kremmel::MoveRobotResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace master_thesis_kremmel

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::master_thesis_kremmel::MoveRobotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master_thesis_kremmel::MoveRobotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::master_thesis_kremmel::MoveRobotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::master_thesis_kremmel::MoveRobotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_thesis_kremmel::MoveRobotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_thesis_kremmel::MoveRobotResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::master_thesis_kremmel::MoveRobotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::master_thesis_kremmel::MoveRobotResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::master_thesis_kremmel::MoveRobotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "master_thesis_kremmel/MoveRobotResponse";
  }

  static const char* value(const ::master_thesis_kremmel::MoveRobotResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::master_thesis_kremmel::MoveRobotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::master_thesis_kremmel::MoveRobotResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::master_thesis_kremmel::MoveRobotResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveRobotResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::master_thesis_kremmel::MoveRobotResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::master_thesis_kremmel::MoveRobotResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MASTER_THESIS_KREMMEL_MESSAGE_MOVEROBOTRESPONSE_H
